// Code generated by MockGen. DO NOT EDIT.
// Source: use_case/data_writer.go

// Package use_case is a generated GoMock package.
package use_case

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataWriter is a mock of DataWriter interface.
type MockDataWriter struct {
	ctrl     *gomock.Controller
	recorder *MockDataWriterMockRecorder
}

// MockDataWriterMockRecorder is the mock recorder for MockDataWriter.
type MockDataWriterMockRecorder struct {
	mock *MockDataWriter
}

// NewMockDataWriter creates a new mock instance.
func NewMockDataWriter(ctrl *gomock.Controller) *MockDataWriter {
	mock := &MockDataWriter{ctrl: ctrl}
	mock.recorder = &MockDataWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataWriter) EXPECT() *MockDataWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockDataWriter) Write(record []Field) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockDataWriterMockRecorder) Write(record interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockDataWriter)(nil).Write), record)
}
